services:
  - type: worker
    name: news-digest
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SENDER_EMAIL
        value: penghaining80@gmail.com
      - key: SENDER_PASSWORD
        value: zjrf vgel yqyd jitl
      - key: RECEIVER_EMAIL
        value: penghaining80@gmail.com
      - key: DEEPSEEK_API_KEY
        value: sk-65ff66cb598e4d4f921883f9e1bee55d
      - key: DEEPSEEK_BASE_URL
        value: https://api.deepseek.com
      - key: SCHEDULE_DAILY_TIME
        value: "08:00"
